name: 'S. Carey'
url: 'http://scarey.org'

exclude: [
  'node_modules',
  'config.rb',
]


shows:
  -
    tourname: April 2014
    support: White Hinterland
    stamp: 2014-05-01 00:00:00 -0800
    dates:
       -
         date: 2014-04-05
         city: Norman, OK
         href: http://opolis.org/
         venue: The Opolis
       -
         date: 2014-04-06
         city: Dallas, TX
         href: http://www.threelinksdeepellum.com/
         venue: Three Links
       -
         date: 2014-04-07
         city: Austin, TX
         href: http://holymountainaustin.com/
         venue: Holy Mountain
       -
         date: 2014-04-09
         city: New Orleans, LA
         href: http://opolis.org/
         venue: Circle Bar
       -
         date: 2014-04-10
         city: Birmingham, AL
         href: http://opolis.org/
         venue: The Bottletree
       -
         date: 2014-04-11
         city: Decatur, GA
         href: http://holymountainaustin.com/
         venue: Eddie's Attic
       -
         date: 2014-04-12
         city: Raleigh, NC
         href: http://opolis.org/
         venue: Kings
       -
         date: 2014-04-13
         city: Washington, DC
         href: http://opolis.org/
         venue: Rock and Roll Hotel
       -
         date: 2014-04-14
         city: Philadelphia, PA
         href: http://holymountainaustin.com/
         venue: Boot & Saddle
       -
         date: 2014-04-16
         city: New York, NY
         href: http://opolis.org/
         venue: Le Poisson Rouge
       -
         date: 2014-04-17
         city: Allston, MA
         href: http://opolis.org/
         venue: Great Scott
       -
         date: 2014-04-18
         city: Montreal, QC
         href: http://holymountainaustin.com/
         venue: Il Motore
       -
         date: 2014-04-19
         city: Toronto, ON
         href: http://opolis.org/
         venue: The Garrison
       -
         date: 2014-04-21
         city: Pontiac, MI
         href: http://opolis.org/
         venue: The Pike Room at The Crofoot
       -
         date: 2014-04-22
         city: Great Rapids, MI
         href: http://opolis.org/
         venue: The Ladies Literary Club
       -
         date: 2014-04-23
         city: Chicago, IL
         href: http://opolis.org/
         venue: Lincoln Hall
       -
         date: 2014-04-24
         city: Milwaukee, WI
         href: http://opolis.org/
         venue: Club Garibaldi
       -
         date: 2014-04-25
         city: Minneapolis, MN
         href: http://opolis.org/
         venue: Cedar Cultural Center
  -
    tourname: May 2013
    stamp: 2013-05-01 00:00:00 -0800
    dates:
       -
         date: 2013-05-01
         city: Spring Green, WI
         href: http://shittybarnsessions.com
         venue: Shitty Barn Sessions
       -
         date: 2013-05-02
         city: Evanston, IL
         venue: Space
       -
         date: 2013-05-04
         city: Iowa City, IA
         venue: The Mill
       -
         date: 2013-05-05
         city: Milwaukee, WI
         venue: Turner Hall
       -
         date: 2013-05-09
         city: Eau Claire, WI
         venue: State Theater Backstage
  -
    tourname: April 2013
    stamp: 2013-04-01 00:00:00 -0800
    dates:
       -
         date: 2013-04-11
         city: Minneapolis, MN
         venue: Ensia Live
         support: Visual Artist Gregory Euclide
  -
    tourname: Jan 2012
    stamp: 2012-01-01 00:00:00 -0800
    dates:
       -
         date: 2013-01-15
         city: Madison, WI
         venue: High Noon Saloon
  -
    tourname: December 2011
    stamp: 2011-12-01 00:00:00 -0800
    dates:
       -
         date: 2011-12-01
         city: Holland, MI
         venue: Knickerbocker Theatre
       -
         date: 2011-12-02
         city: Chicago, IL
         venue: Schubas
       -
         date: 2011-12-03
         city: Ames, IA
         venue: Maintenance Shop
  -
    tourname: June/July 2011
    support: David Bazan
    stamp: 2011-08-01 00:00:00 -0800
    dates:
       -
         date: 2011-06-19
         city: Cambridge, MA
         venue: TT the Bears
       -
         date: 2011-06-22
         city: New York, NY
         venue: Bowery Ballroom
       -
         date: 2011-06-23
         city: Philadelphia, PA
         venue: Johnny Brenda's
       -
         date: 2011-06-24
         city: Washington, DC
         venue: Black Cat
       -
         date: 2011-06-27
         city: Orlando, FL
         venue: The Social
       -
         date: 2011-06-28
         city: Atlanta, GA
         venue: The Earl
       -
         date: 2011-06-29
         city: Birmingham, AL
         venue: The Bottletree
       -
         date: 2011-06-30
         city: New Orleans, LA
         venue: One Eyed Jacks
       -
         date: 2011-07-01
         city: Baton Rouge, LA
         venue: Spanish Moon
  -
    tourname: May 2011
    support: Other Lives
    stamp: 2011-06-01 00:00:00 -0800
    dates:
       -
         date: 2011-05-07
         city: Fargo, ND
         venue: The Aquarium
       -
         date: 2011-05-12
         city: Madison, WI
         venue: High Noon Saloon
       -
         date: 2011-05-13
         city: Iowa City, IA
         venue: The Mill
       -
         date: 2011-05-14
         city: Omaha, NE
         venue: Slowdown Jr.
       -
         date: 2011-05-15
         city: Denver, CO
         venue: Hi Dive
       -
         date: 2011-05-18
         city: Tucson, AZ
         venue: Club Congress
       -
         date: 2011-05-19
         city: San Diego, CA
         venue: Soda Bar
       -
         date: 2011-05-20
         city: Santa Barbara, CA
         venue: Velvet Jones
       -
         date: 2011-05-21
         city: Los Angeles, CA
         venue: Satellite Club
       -
         date: 2011-05-22
         city: Big Sur, CA
         venue: Henry Miller Library
       -
         date: 2011-05-24
         city: San Francisco, CA
         venue: Cafe du Nord
       -
         date: 2011-05-25
         city: Davis, CA
         venue: Sophia's Thai Kitchen
       -
         date: 2011-05-26
         city: Portland, OR
         venue: Doug Fir Lounge
       -
         date: 2011-05-27
         city: Bellingham, WA
         venue: Pandaland
       -
         date: 2011-05-29
         city: George, WA
         venue: Sasquatch Music Festival
       -
         date: 2011-05-30
         city: Missoula, MT
         venue: The Badlander
  -
    tourname: March/April 2011
    stamp: 2011-05-01 00:00:00 -0800
    dates:
       -
         date: 2011-03-30
         city: Bloomington, IN
         venue: The Bishop
       -
         date: 2011-03-31
         city: Cleveland, OH
         venue: Beachland, Tavern
       -
         date: 2011-04-01
         city: Harrisonburg, VA
         venue: Court Square Theatre / MACRoCK
       -
         date: 2011-04-02
         city: Raleigh, NC
         venue: Kings Barcade
       -
         date: 2011-04-03
         city: Nashville, TN
         venue: The Basement
       -
         date: 2011-04-04
         city: St. Louis, MO
         venue: Off Broadway
  -
    tourname: February 2011
    stamp: 2011-03-01 00:00:00 -0800
    support: Yann Tiersen
    dates:
       -
         date: 2011-02-02
         city: Dallas, TX
         venue: The Loft
       -
         date: 2011-02-03
         city: Austin, TX
         venue: The Mohawk
       -
         date: 2011-02-04
         city: Houston, TX
         venue: Fitzgerald's
       -
         date: 2011-02-05
         city: New Orleans, LA
         venue: The Republic
       -
         date: 2011-02-07
         city: Tallahassee, FL
         venue: Club Downunder
       -
         date: 2011-02-08
         city: Orlando, FL
         venue: The Social
  -
    tourname: Januray 2011
    stamp: 2011-03-01 00:00:00 -0800
    dates:
       -
         date: 2011-01-14
         city: Minneapolis, MN
         venue: Varsity Theater
         support: The Daredevil Christopher Wright
       -
         date: 2011-01-15
         city: Milwaukee, WI
         venue: Club Garibaldi
         support: Conrad Plymouth
       -
         date: 2011-01-16
         city: Chicago, IL
         venue: Schubas / Tomorrow NEver Knows Festival
       -
         date: 2011-01-25
         city: Duluth, MN
         venue: University of Minnesota, Duluth
         support: Sarah Krueger
  -
    tourname: December 2010
    stamp: 2011-01-01 00:00:00 -0800
    support: White Hinterland
    dates:
       -
         date: 2010-12-09
         city: Eau Claire, WI
         venue: State Theater Backstage
         support: Peter Wolf Crier
       -
         date: 2011-12-10
         city: Iowa City, IA
         venue: The Mill
       -
         date: 2011-12-11
         city: Cincinnati, OH
         venue: Mayday
       -
         date: 2011-12-13
         city: New York, NY
         venue: Highline Ballroom
       -
         date: 2010-12-14
         city: Washington, DC
         venue: Rock and Roll Hotel
       -
         date: 2011-12-15
         city: Philadelphia, PA
         venue: First Unitarian Chapel
       -
         date: 2011-12-16
         city: Boston, MA
         venue: Paramount Center Black Box
       -
         date: 2011-12-17
         city: Portland, ME
         venue: Space
       -
         date: 2011-12-18
         city: Montreal, QC
         venue: Casa Del Popolo
       -
         date: 2011-12-19
         city: Toronto, ON
         venue: Horseshoe Tavern
  -
    tourname: September/October 2010
    stamp: 2010-11-01 00:00:00 -0800
    support: The Tallest Man On Earth
    dates:
       -
         date: 2010-09-08
         city: Vancouver, BC
         venue: Rickshaw Theatre
       -
         date: 2010-09-09
         city: Seattle, WA
         venue: Neumos
       -
         date: 2010-09-10
         city: Portland, OR
         venue: Doug Fir Lounge
       -
         date: 2010-09-12
         city: Big Sur, CA
         venue: Henry Miller Library
       -
         date: 2010-09-13
         city: San Francisco, CA
         venue: The Fillmore
       -
         date: 2010-09-14
         city: Los Angeles, CA
         venue: The Music Box
       -
         date: 2010-09-15
         city: Tucson, AZ
         venue: Club Congress
       -
         date: 2010-09-17
         city: Dallas, TX
         venue: House of Blues - Pontiac Garage
       -
         date: 2010-09-18
         city: Austin, TX
         venue: Antone's
       -
         date: 2010-09-24
         city: Toronto, ON
         venue: Lee's Palace
       -
         date: 2010-09-25
         city: Montreal, QC
         venue: Le National
       -
         date: 2010-09-27
         city: New York, NY
         venue: Webster Hall
       -
         date: 2010-10-02
         city: Philadelphia, PA
         venue: Theatre of Living Arts
       -
         date: 2010-10-03
         city: Washington, DC
         venue: "9:30 Club"